### ISSUE TITLE
Promise interface, onRejected ?

### ISSUE THREAD

**Issue by eddycharly** [auxmoney/OpentracingBundle-Guzzle#17]
In `GuzzleRequestSpanning`, isn't the `$onRejected` callback missing ?

https://github.com/auxmoney/OpentracingBundle-Guzzle/blob/ced155c3335adf4341e22365470f5aa302dc16ef/Middleware/GuzzleRequestSpanning.php#L31-L37

See the relevant interface here:
https://github.com/guzzle/promises/blob/89b1a76b7fda5853401297dc4b2a093cba1fda23/src/PromiseInterface.php#L28-L31

I fear that if the request is canceled or in case of an error, the open span won't be closed.

**Comment by cawolf** [comment]
Good catch! Do you want to improve that part?

Do you know if Guzzle provides the tools to simulate this behavior (for adding a functional test case)?

**Comment by eddycharly** [comment]
No idea if Guzzle provides some tools to simulate the behavior.
Maybe just trying to call an url that has an invalid scheme ?

I will open a PR later.
